development:
  adapter: postgresql
  encoding: unicode
  database: survey_project_dev
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: survey_project_test
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: survey_project_production
  pool: 5
  username: postgres
  password: password
